### ISSUE TITLE
java.lang.NoClassDefFoundError mqtt3.Mqtt3PublishView

### ISSUE THREAD

**Issue by ThePutzy** [hivemq/hivemq-mqtt-client#433]
## Actual behavior
```
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.publish.mqtt3.-$$Lambda$x0wx2KKs7pTgqn1ySiq8F7I9MLg>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.publish.mqtt3.-$$Lambda$x0wx2KKs7pTgqn1ySiq8F7I9MLg>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.publish.mqtt3.-$$Lambda$2KJUmemIE1iKPCVPHhr-c6sg5kM>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.publish.mqtt3.-$$Lambda$2KJUmemIE1iKPCVPHhr-c6sg5kM>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.publish.mqtt3.-$$Lambda$2KJUmemIE1iKPCVPHhr-c6sg5kM>
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: com.hivemq.client.internal.mqtt.message.publish.mqtt3.-$$Lambda$2KJUmemIE1iKPCVPHhr-c6sg5kM
        at com.hivemq.client.internal.mqtt.message.publish.mqtt3.Mqtt3PublishView.<clinit>(Mqtt3PublishView.java:45)
        at com.hivemq.client.internal.mqtt.message.publish.mqtt3.Mqtt3PublishViewBuilder$Base.build(Mqtt3PublishViewBuilder.java:104)
        at com.hivemq.client.internal.mqtt.message.publish.mqtt3.Mqtt3PublishViewBuilder$Default.build(Mqtt3PublishViewBuilder.java:108)
        at de.xyz.protect.network.MqClient.<init>(MqClient.kt:84)
```

## build.gradle
```
buildscript {
    ext.kotlin_version = '1.3.72'

    repositories {
        google()
        jcenter()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'

        // Kotlin
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"

        // Google services
        classpath 'com.google.gms:google-services:4.3.3'

        // HiveMQ
        classpath 'gradle.plugin.com.github.sgtsilvio.gradle:android-retrofix:0.3.6'
    }
}

allprojects {
    repositories {
        google()
        jcenter()

        // Kotlin serialization
        maven {
            url "https://kotlin.bintray.com/kotlinx"
        }

        // Fuel
        maven {
            url = "https://jitpack.io"
            name = "jitpack"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlinx-serialization'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'com.github.sgtsilvio.gradle.android-retrofix'

android {
    compileSdkVersion 30

    defaultConfig {
        applicationId "de.xyz.protect"
        minSdkVersion 22
        targetSdkVersion 30
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        versionName "1.1.2"

        //noinspection HighAppVersionCode
        versionCode 2020072715

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.incremental": "true"]
            }
        }
    }

    buildTypes {
        release {
            debuggable = false
            jniDebuggable = false
            renderscriptDebuggable = false

            minifyEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix = '.debug'
            debuggable = true
            jniDebuggable = true
            renderscriptDebuggable = true
            versionNameSuffix = '-alpha'

            minifyEnabled = false
        }
    }

    sourceSets {
        main {
            res.srcDirs =
                    [
                            'src/main/res/layouts/activities',
                            'src/main/res/layouts/contents',
                            'src/main/res/layouts/fragments',
                            'src/main/res/layouts/overlays',
                            'src/main/res/layouts/recycler',
                            'src/main/res/layouts',
                            'src/main/res'
                    ]
        }
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    compileOptions {
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/io.netty.versions.properties'
    }
}

dependencies {
    def fuel_version = "2.0.1"
    def log4k_version = "1.0.1"
    def room_version = '2.2.5'
    def lifecycle_version = '2.2.0'

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.14.0"
    implementation "org.jetbrains.kotlin:kotlin-reflect:${kotlin_version}"
    implementation 'androidx.core:core-ktx:1.3.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation "androidx.legacy:legacy-support-v4:1.0.0"
    implementation "androidx.constraintlayout:constraintlayout:1.1.3"
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
    implementation "androidx.room:room-runtime:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    implementation 'androidx.work:work-runtime-ktx:2.3.4'
    implementation "androidx.preference:preference-ktx:1.1.1"
    implementation 'com.google.android.material:material:1.3.0-alpha01'
    implementation "com.google.android.gms:play-services-location:17.0.0"
    implementation "com.google.firebase:firebase-analytics-ktx:17.4.4"
    implementation 'com.google.firebase:firebase-messaging:20.2.3'
    implementation "com.google.firebase:firebase-perf:19.0.8"
    implementation 'com.google.firebase:firebase-crashlytics:17.1.1'
    implementation "com.log4k:log4k:$log4k_version"
    implementation "com.log4k:log4k-android:$log4k_version"
    implementation "com.github.kittinunf.fuel:fuel:$fuel_version"
    implementation "com.github.kittinunf.fuel:fuel-coroutines:$fuel_version"
    implementation "com.github.kittinunf.fuel:fuel-android:$fuel_version"
    implementation "com.github.kittinunf.fuel:fuel-gson:$fuel_version"
    implementation "com.github.kittinunf.fuel:fuel-livedata:$fuel_version"
    implementation "com.github.kittinunf.fuel:fuel-kotlinx-serialization:$fuel_version"
    implementation "commons-codec:commons-codec:1.14"
    implementation 'com.jakewharton.threetenabp:threetenabp:1.2.4'
    implementation 'me.itangqi.waveloadingview:library:0.3.5'

    implementation 'com.hivemq:hivemq-mqtt-client:1.2.0'
    implementation 'net.sourceforge.streamsupport:android-retrostreams:1.7.2'
    implementation 'net.sourceforge.streamsupport:android-retrofuture:1.7.2'

    implementation 'com.github.judemanutd:autostarter:1.0.8'
    api "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2"
    api "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.0"
    kapt "androidx.room:room-compiler:$room_version"
    testImplementation 'junit:junit:4.13'
    testImplementation "androidx.room:room-testing:$room_version"
    androidTestImplementation "androidx.test:runner:1.2.0"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.2.0"
    androidTestImplementation "androidx.arch.core:core-testing:2.1.0"
    androidTestImplementation "androidx.room:room-testing:$room_version"
    androidTestImplementation 'androidx.work:work-testing:2.3.4'
}
```

### Reproducer code
This will crash the app:
```
// Build last will message
val lastWillMessage = Mqtt3Publish.builder()
  .topic(lwTopic)
  .qos(MqttQos.AT_LEAST_ONCE)
  .payload("false".toByteArray())
  .retain(true)
  .build() <- MqClient.kt:84
```

If i comment it out the crash will be appear at simpleAuth:
```
client = MqttClient.builder()
                .useMqttVersion3()
                .identifier(mqttClientId)
                .serverHost(serverHost!!)
                .serverPort(serverPort!!)
                .sslWithDefaultConfig()
                .automaticReconnectWithDefaultConfig()
                .simpleAuth() <- Crash if lastWill deactivated
                .username(mqttUser!!)
                .password(mqttPass!!.toByteArray())
                .applySimpleAuth()
                .buildBlocking()
```

## Details
Device: Android 6.0.1

Android Studio 4.0.1 Build #AI-193.6911.18.40.6626763 June 25, 2020
Java version: 1.8.0_242-release-1644-b3-6222593x86_64
Operating System: Mac OS X (10.15.6, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

**Comment by ThePutzy** [comment]
I tried also set "coreLibraryDesugaringEnabled"
```
compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

dependencies {
...
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.9'
...
}
```

## Error
```
I/art: Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.logging.Log4J2Logger>
I/art: Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.logging.Log4J2Logger>
I/art: Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.logging.Log4J2Logger>
I/art: Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.LongAdderCounter>
I/art: Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.LongAdderCounter>
I/PlatformDependent: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/concurrent/CompletableFuture;
        at com.hivemq.client.internal.mqtt.mqtt3.Mqtt3AsyncClientView.connect(Mqtt3AsyncClientView.java:96)
        at com.hivemq.client.internal.mqtt.mqtt3.-$$Lambda$-b-bih_w_E9ICjl-9w-tg0l2dVg.apply(lambda)
        at com.hivemq.client.internal.mqtt.message.connect.mqtt3.Mqtt3ConnectViewBuilder$Send.send(Mqtt3ConnectViewBuilder.java:152)
        at de.xyz.protect.network.MqClient.connect(MqClient.kt:173)
        at de.xyz.protect.network.MqClient.<init>(MqClient.kt:161)
        at de.xyz.protect.services.MainService.onCreate(MainService.kt:133)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3873)
        at android.app.ActivityThread.access$2100(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1909)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.concurrent.CompletableFuture" on path: DexPathList[[zip file "/data/app/de.xyz.protect.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/de.xyz.protect.debug-2/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.hivemq.client.internal.mqtt.mqtt3.Mqtt3AsyncClientView.connect(Mqtt3AsyncClientView.java:96) 
        at com.hivemq.client.internal.mqtt.mqtt3.-$$Lambda$-b-bih_w_E9ICjl-9w-tg0l2dVg.apply(lambda) 
        at com.hivemq.client.internal.mqtt.message.connect.mqtt3.Mqtt3ConnectViewBuilder$Send.send(Mqtt3ConnectViewBuilder.java:152) 
        at de.xyz.protect.network.MqClient.connect(MqClient.kt:173) 
        at de.xyz.protect.network.MqClient.<init>(MqClient.kt:161) 
        at de.xyz.protect.services.MainService.onCreate(MainService.kt:133) 
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3873) 
        at android.app.ActivityThread.access$2100(ActivityThread.java:229) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1909) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:7406) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
    	Suppressed: java.lang.ClassNotFoundException: java.util.concurrent.CompletableFuture
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 16 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

```

**Comment by SgtSilvio** [comment]
Hi @ThePutzy 
> java.lang.NoClassDefFoundError: com.hivemq.client.internal.mqtt.message.publish.mqtt3.-$$Lambda$2KJUmemIE1iKPCVPHhr-c6sg5kM

This indicates that lambdas are not properly desugared.
Normally the following configuration should enable this:
```groovy
android {
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
  kotlinOptions {
    jvmTarget = "1.8"
  }
}
```
As you have already included this in your build.gradle, maybe there is a problem with Kotlin an Java.
Could you try replacing the Kotlin code that uses the client with Java code to verify this?

Regarding your second comment:
I do not know if the `coreLibraryDesugaringEnabled` is compatible with `android-retrofix`.
Also `coreLibraryDesugaringEnabled` is not enough because it does not desugar `CompletableFuture` for example.
So please remove `coreLibraryDesugaringEnabled` and only use `android-retrofix`.

**Comment by ThePutzy** [comment]
Hi @SgtSilvio,
thank you, for your fast response.
I tried it in Java now, but unfortunately the same result.
`coreLibraryDesugaring` is disabled.

### Error
```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: com.hivemq.client.internal.mqtt.message.publish.mqtt3.-$$Lambda$2KJUmemIE1iKPCVPHhr-c6sg5kM
        at com.hivemq.client.internal.mqtt.message.publish.mqtt3.Mqtt3PublishView.<clinit>(Mqtt3PublishView.java:44)
        at com.hivemq.client.internal.mqtt.message.publish.mqtt3.Mqtt3PublishViewBuilder$Base.build(Mqtt3PublishViewBuilder.java:103)
        at com.hivemq.client.internal.mqtt.message.publish.mqtt3.Mqtt3PublishViewBuilder$Default.build(Mqtt3PublishViewBuilder.java:107)
        at de.xyz.protect.network.JavaMqClient.main(JavaMqClient.java:37)
        at de.xyz.protect.services.MainService.onCreate(MainService.kt:137)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3873)
        at android.app.ActivityThread.access$2100(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1909)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

### The part where it thrown:
```
final Mqtt3Publish lastWillMessage = Mqtt3Publish.builder()
                .topic(lwTopic)
                .qos(MqttQos.AT_LEAST_ONCE)
                .payload("false".getBytes())
                .retain(true)
                .build();
```

Best regards from Munich
Steven

**Comment by ThePutzy** [comment]
### I've found a solution. ;-)

Old order:
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlinx-serialization'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'com.github.sgtsilvio.gradle.android-retrofix'
```

New order (that fixes the error):
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlinx-serialization'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.github.sgtsilvio.gradle.android-retrofix'
apply plugin: 'com.google.firebase.firebase-perf'
```

It seems that `retrofix` can't behind firebase-perf.

**Comment by SgtSilvio** [comment]
Glad to hear that you could solve your problem.
Thank you for letting us know that the `firebase-perf` plugin needs to be applied after the `android-retrofix` plugin.
