### ISSUE TITLE
Netty warning with MqttClient.builder() using JDK 9+

### ISSUE THREAD

**Issue by jadbaz** [hivemq/hivemq-mqtt-client#473]
## Expected behavior
No warnings

## Actual behavior
```
13:01:53.724 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:225) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:219) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.NetUtil$1.run(NetUtil.java:260) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.NetUtil$1.run(NetUtil.java:253) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at io.netty.util.NetUtil.<clinit>(NetUtil.java:253) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at com.hivemq.client.internal.util.InetSocketAddressUtil.create(InetSocketAddressUtil.java:32) [hivemq-mqtt-client-1.2.1.jar:?]
	at com.hivemq.client.internal.mqtt.MqttClientTransportConfigImpl.<clinit>(MqttClientTransportConfigImpl.java:34) [hivemq-mqtt-client-1.2.1.jar:?]
	at com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase.<init>(MqttRxClientBuilderBase.java:46) [hivemq-mqtt-client-1.2.1.jar:?]
	at com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$Choose.<init>(MqttRxClientBuilderBase.java:216) [hivemq-mqtt-client-1.2.1.jar:?]
	at com.hivemq.client.mqtt.MqttClient.builder(MqttClient.java:59) [hivemq-mqtt-client-1.2.1.jar:?]
	at Main.main(Main.java:5) [main/:?]
13:01:53.739 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
13:01:53.740 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @48793bef
	at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:558) ~[?:?]
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:335) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:326) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.NetUtil$1.run(NetUtil.java:260) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.NetUtil$1.run(NetUtil.java:253) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at io.netty.util.NetUtil.<clinit>(NetUtil.java:253) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at com.hivemq.client.internal.util.InetSocketAddressUtil.create(InetSocketAddressUtil.java:32) [hivemq-mqtt-client-1.2.1.jar:?]
	at com.hivemq.client.internal.mqtt.MqttClientTransportConfigImpl.<clinit>(MqttClientTransportConfigImpl.java:34) [hivemq-mqtt-client-1.2.1.jar:?]
	at com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase.<init>(MqttRxClientBuilderBase.java:46) [hivemq-mqtt-client-1.2.1.jar:?]
	at com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$Choose.<init>(MqttRxClientBuilderBase.java:216) [hivemq-mqtt-client-1.2.1.jar:?]
	at com.hivemq.client.mqtt.MqttClient.builder(MqttClient.java:59) [hivemq-mqtt-client-1.2.1.jar:?]
	at Main.main(Main.java:5) [main/:?]
13:01:53.741 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
```

### Steps
Simply run `MqttClient.builder();` with JDK 9+ and an SLF4J impl

### Reproducer code
```
import com.hivemq.client.mqtt.MqttClient;

public class Main {
    public static void main(String[] args) {
        MqttClient.builder();
    }
}
```

Or check out the reproducer at: https://github.com/jadbaz/hivemq-netty-issue-reproducer

## Details
- Affected HiveMQ MQTT Client version(s): 1.2.1
- Used JVM version: OpenJDK 8, AdoptOpenJDK 11
- Used OS (name and version): Windows 10
- Used MQTT version: N/A
- Used MQTT broker (name and version): N/A

## References
- This [SO answer](https://stackoverflow.com/a/60241952)

**Comment by SgtSilvio** [comment]
Hi @jadbaz 
This is only debug logging from netty when it tries to find out if special optimizations are available. The client works nonetheless.
Here a direct quote from the netty team:
> It's not an error, it's a debug message with a stacktrace, change your logger level to something else apart from debug eg. info or warn.
(https://github.com/netty/netty/issues/7817)

Because this is not an issue, I close it now.
Please feel free to comment if you have additional questions.
