### ISSUE TITLE
Async MQTT client blocks on publish if the client is disconnected and waiting between reconnect attempts

### ISSUE THREAD

**Issue by richturner** [hivemq/hivemq-mqtt-client#554]
## Expected behavior
The async client (in my case `Mqtt3AsyncClient`) should not block when calling `send` no matter what the client state is; instead I would expect to get the `CompletableFuture<MqttPublish>`

## Actual behavior
`send` blocks the calling thread; I guess waiting for the client to be in a connected state?

## To Reproduce
1. Create an Mqtt3AsyncClient with reconnect logic, put an invalid host value (so the client can never actually connect)
2. Publish an MQTT message e.g.:
```
client.publishWith()
            .topic(message.topic)
            .payload(messageToBytes(message.payload))
            .send()
            .whenComplete((publish, throwable) -> {
                if (throwable != null) {
                    // Failure
                    LOG.log(Level.INFO, "Failed to publish to MQTT broker '" + getClientUri() + "'", throwable);
                } else {
                    // Success
                    LOG.finer("Published message to MQTT broker '" + getClientUri() + "'");
                }
            });
```
3. Notice that the call blocks on the `send` call with no `Future` ever returned

## Details
- Affected HiveMQ MQTT Client version(s): 1.2.2
- Used JVM version: Oracle JDK 17.0.1
- Used OS (name and version): Windows 10 64-bit but also same behaviour on Linux Debian AArch64
- Used MQTT version: N/A
- Used MQTT broker (name and version): N/A

**Comment by pglombardo** [comment]
Hi @richturner - thanks for pointing this issue out.  I'll see if I can reproduce this here locally and report back soon.

**Comment by pglombardo** [comment]
Hi @richturner - I haven't been able to reproduce this.  Could you post your client creation code (with reconnect)?

**Comment by pglombardo** [comment]
Since this issue has gone stale, I'll close it out but if you want to pick up on this again, let us know.  We'd be happy to help out!

**Comment by Mystery406** [comment]
Same problem here, have you found any solutions to this?

**Comment by Blafasel3** [comment]
It seems we are experiencing the same issue with an RxClient:

It seems the connect runs into a timeout and the client does not recover from that.
This essentially leads to a memory leak (with unbounded thread count) or a totally blocked app (with bounded thread count)

This is the creation Logic we use:
The variable `connectionDetails` is just a data class wrapping some config. Initial reconnect delay is 1 seconds, max is 1 minute.
```
MqttClient.builder().useMqttVersion3().identifier(connectionDetails.clientProperties.identifier())
			// Server-Settings
			.serverHost(connectionDetails.serverProperties.serverHost).serverPort(connectionDetails.serverProperties.serverPort)
			.also {
				val authDetails = connectionDetails.authorization
				if (authDetails != null) {
					it.simpleAuth().username(authDetails.username).password(authDetails.password.toByteArray()).applySimpleAuth()
				}
			}
			// Reconnect-Settings
			.automaticReconnect()
			.initialDelay(connectionDelayInMillis, TimeUnit.MILLISECONDS)
			.maxDelay(reconnectMaxDelayInMillis, TimeUnit.MILLISECONDS)
			.applyAutomaticReconnect()
			// Listener Configurations
			.addConnectedListener(connectedLister)
			.addDisconnectedListener(disconnectedListener)
			.buildRx()
```

**Comment by thxyoulistenme** [comment]
@Mystery406 @Blafasel3 Hi, We also encountered the same problem, do you have a solution? Thank you so much

**Comment by Mystery406** [comment]
> @richturner @Mystery406 @Blafasel3 Hi, We also encountered the same problem, do you have a solution? Thank you so much

My workaround for now is to check whether client is connected to server before every push.

**Comment by code2life-crypto** [comment]
@richturner @Mystery406 @Blafasel3 @pglombardo @richturner  Hi, we are facing the same issue, and we check the client state before each send. Here is the code for publish message:
<img width="1225" alt="ts20241012-1152-2" src="https://github.com/user-attachments/assets/d945aa77-eb32-4920-93fa-a3d1941e4789">

Under most circumstances, it runs fine in prod env. This is an intermittent issue that has occurred twice in the past six months, where the thread gets locked and cannot be awakened.

here is a sample stack trace:
`"***.client.pool-2-2" #157 [111] prio=5 os_prio=0 cpu=3198.07ms elapsed=100922.67s tid=0x00007fd7fbfac520 nid=111 in Object.wait()  [0x00007fd77e3f1000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait0(java.base@21.0.2/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@21.0.2/Object.java:366)
	at java.lang.Object.wait(java.base@21.0.2/Object.java:339)
	at com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables.add(MqttPublishFlowables.java:53)
	- locked <0x00000007220c0a30> (a com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables)
	at com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttAckSingle.subscribeActual(MqttAckSingle.java:56)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.hivemq.client.internal.rx.RxFutureConverter$RxSingleFuture.<init>(RxFutureConverter.java:113)
	at com.hivemq.client.internal.rx.RxFutureConverter.toFuture(RxFutureConverter.java:43)
	at com.hivemq.client.internal.mqtt.MqttAsyncClient.publish(MqttAsyncClient.java:243)`
	
      **### Details**
      Affected HiveMQ MQTT Client version(s): 1.3.0
      Used JVM version: Oracle JDK 21+
      Used OS (name and version): deploy on AWS cloud Linux Debian AArch64
      Used MQTT version: N/A
      Used MQTT broker (name and version): N/A

Could you please help investigate this issue?

**Comment by Blafasel3** [comment]
> @richturner @Mystery406 @Blafasel3 @pglombardo @richturner Hi, we are facing the same issue, and we check the client state before each send. Here is the code for publish message: <img alt="ts20241012-1152-2" width="1225" src="https://private-user-images.githubusercontent.com/184713792/375921440-d945aa77-eb32-4920-93fa-a3d1941e4789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3Mzc1NDEsIm5iZiI6MTcyODczNzI0MSwicGF0aCI6Ii8xODQ3MTM3OTIvMzc1OTIxNDQwLWQ5NDVhYTc3LWViMzItNDkyMC05M2ZhLWEzZDE5NDFlNDc4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMjQ3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmE5Nzc1ZGRhMWI2MTQ5ODIzNDdkZmE2M2RhZjExN2RlOGQ5NDE4MjA5NmZmYzIwM2ZlZmU1MzMwMTRhMjg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f1dX-S8krRhBqP5J8srVU56EXQwbvqR6aQb6I6FmAQU">
> 
> Under most circumstances, it runs fine in prod env. This is an intermittent issue that has occurred twice in the past six months, where the thread gets locked and cannot be awakened.
> 
> here is a sample stack trace: `"**.client.pool-2-2" #157 [111] prio=5 os_prio=0 cpu=3198.07ms elapsed=100922.67s tid=0x00007fd7fbfac520 nid=111 in Object.wait() [0x00007fd77e3f1000] java.lang.Thread.State: WAITING (on object monitor) at java.lang.Object.wait0(java.base@21.0.2/Native Method) - waiting on <no object reference available> at java.lang.Object.wait(java.base@21.0.2/Object.java:366) at java.lang.Object.wait(java.base@21.0.2/Object.java:339) at com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables.add(MqttPublishFlowables.java:53) - locked <0x00000007220c0a30> (a com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables) at com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttAckSingle.subscribeActual(MqttAckSingle.java:56) at io.reactivex.Single.subscribe(Single.java:3666) at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35) at io.reactivex.Single.subscribe(Single.java:3666) at com.hivemq.client.internal.rx.RxFutureConverter$RxSingleFuture.<init>(RxFutureConverter.java:113) at com.hivemq.client.internal.rx.RxFutureConverter.toFuture(RxFutureConverter.java:43) at com.hivemq.client.internal.mqtt.MqttAsyncClient.publish(MqttAsyncClient.java:243)`
> 
> here is "com.hivemq.client.mqtt" stack trace: `"com.hivemq.client.mqtt-7-1" #176 [121] prio=10 os_prio=0 cpu=998.73ms elapsed=100918.76s tid=0x00007fd65c2a5220 nid=121 runnable [0x00007fd77dceb000] java.lang.Thread.State: RUNNABLE at io.netty.channel.epoll.Native.epollWait0(Native Method) at io.netty.channel.epoll.Native.epollWait(Native.java:193) at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:304) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:368) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.runWith(java.base@21.0.2/Thread.java:1596) at java.lang.Thread.run(java.base@21.0.2/Thread.java:1583)
> 
> "com.hivemq.client.mqtt-7-2" #175 [122] prio=10 os_prio=0 cpu=1038.93ms elapsed=100918.76s tid=0x00007fd674412360 nid=122 runnable [0x00007fd77dbea000] java.lang.Thread.State: RUNNABLE at io.netty.channel.epoll.Native.epollWait0(Native Method) at io.netty.channel.epoll.Native.epollWait(Native.java:193) at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:304) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:368) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.runWith(java.base@21.0.2/Thread.java:1596) at java.lang.Thread.run(java.base@21.0.2/Thread.java:1583)`
> 
> ```
>   **### Details**
>   Affected HiveMQ MQTT Client version(s): 1.3.0
>   Used JVM version: Oracle JDK 21+
>   Used OS (name and version): deploy on AWS cloud Linux Debian AArch64
>   Used MQTT version: N/A
>   Used MQTT broker (name and version): N/A
> ```
> 
> We can't reproduce the issue in our local env, even after trying with breakpoints. We suspect that HiveMQ's thread pool doesn't always call the notifyAll method in certain cases, but we're unsure of the cause. <img alt="ts20241012-1210-2" width="1446" src="https://private-user-images.githubusercontent.com/184713792/375923915-5a64c61e-5434-454d-b85d-6a398d2ef573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3Mzc1NDEsIm5iZiI6MTcyODczNzI0MSwicGF0aCI6Ii8xODQ3MTM3OTIvMzc1OTIzOTE1LTVhNjRjNjFlLTU0MzQtNDU0ZC1iODVkLTZhMzk4ZDJlZjU3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMjQ3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjQ3Yjg4YzkwYzBjZGIzY2YyMTAyMTNkZWRhNTE3ODA2ZWMzNGE5NGE0ZDgyYmZkYTkxM2IzNjg2NjMwMDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.e9b7O6tbrOvjfFq3F_2WcoNSR6nIG1GvR0DU0S0qujE">
> 
> Could you please help investigate this issue?

@Mystery406 @thxyoulistenme  
This is basically what we are doing now. You could consider implementing a queue like this depending on QoS.
But nevertheless, this should be fixed inside the client imo.

**Comment by joggeli34** [comment]
We have a quite similar problem. When we start our service which subscribes to a lot of topics during startup, it can happen that the publishes get blockt. We are not sure if it also has to do with a disconnect or just by overloading the connection and then running into some kind of timeout blocking the publish.

**Comment by 0BuRner** [comment]
Hi, any news on this ?
Isn't it related to the fact that CompletableFuture.orTimeout() doesn't effectively stop the thread ? The TimeoutException is only an indicator that it took too long.
What if the publish/send is blocked for any (most probably network) reason ? The thread is blocked indefinitely waiting for a response ?! Or is there internal mechanism to the hivemq client that will forcely release the thread/close the connection in such case ?

**Comment by andy-todd-dev** [comment]
Having a similar issue. Any news on an investigation or fix? Thanks

```kotlin
 coroutineScope.launch {
            val client = Mqtt3Client.builder()
                .identifier("FilamentLoader-${printer.serialNumber}")
                .serverHost(printer.ipAddress)
                .serverPort(MQTT_PORT)
                .sslConfig(
                    MqttClientSslConfig.builder()
                        .trustManagerFactory(trustManagerFactory)
                        // TODO: Implement SNI correctly (printer serial)
                        .hostnameVerifier { hostname, session -> true }
                        .build()
                )
                .simpleAuth(
                    Mqtt3SimpleAuth.builder()
                        .username(authenticationDetails.username)
                        .password(authenticationDetails.accessCode.encodeToByteArray())
                        .build()
                )
                .buildAsync()

            Log.d("MQTT", "Connecting to ${printer.name}")
            client.connect().await()

            Log.d("MQTT", "Subscribing to ${printer.reportTopic()}")
            client.subscribeWith()
                .topicFilter(printer.reportTopic())
                .qos(MqttQos.AT_LEAST_ONCE)
                .callback { message ->
                    message.payload.map {
                        Log.d(
                            "MQTT",
                            "Received message: ${StandardCharsets.UTF_8.decode(it)}"
                        )
                    }

                }
                .send().await()

            Log.d("MQTT", "Publishing to ${printer.requestTopic()}")
            client.publishWith()
                .topic(printer.requestTopic())
                .qos(MqttQos.AT_LEAST_ONCE)
                .payload(Json.encodeToString(pushAllDataRequestJson).encodeToByteArray())
                .send().await() // <------ This call never returns

            Log.d("MQTT", "Waiting...")
            delay(MAXIMUM_CONNECTION_TIME)
            Log.d("MQTT", "Disconnecting from ${printer.name}")
            client.disconnect().await()
        }
```

**Comment by Blafasel3** [comment]
I feel like this is kind of unsolveable if strictly adhering to the Mqtt v3 protocol. Its exactly the reason why ttl in Mqtt V5 exists.
My suggestion is to introduce like a global timeout for messages if they cannot get published with a default of infinity and configurable via properties.

**Comment by andy-todd-dev** [comment]
> I feel like this is kind of unsolveable if strictly adhering to the Mqtt v3 protocol. Its exactly the reason why ttl in Mqtt V5 exists. My suggestion is to introduce like a global timeout for messages if they cannot get published with a default of infinity and configurable via properties.

In my example at least the message *does* get published. The Future just never completes

**Comment by tpiec-rite** [comment]
I am sorry to awake this old topic but I have the same issue as mentioned here. I am using Mqtt5ClientBuilder with automaticReconnect() and when I try to publish message during reconnect, send() is stuck and is not returning CompletableFuture<Mqtt5PublishResult>. This causes thread "starvation" and calls are not possible to execute.

I tried to add .orTimeout() to it but it does not work.
I use newest version of library (hivemq-mqtt-client) 1.3.15
I can't use isConnected() before publish becasue I can't relay on it in docker environemnt - sometimes it returns true when connection is down. We need to relay on autoreconnect feature.

**Comment by Blafasel3** [comment]
@SgtSilvio @pglombardo I believe this should get more attention. We actually had a production outage twice in different applications because of this unchangeable behaviour and there is literally nothing to be done on the users side. Imo this is a severe bug.

**Comment by mschoenert-hivemq** [comment]
Thanks for the detailed reports and for your patience — a proper explanation is overdue. (This applies to #620 as well; see the note at the end.)

**The short version:** the async `send()` blocks while the client is disconnected/reconnecting because, with that API, blocking is the only safe thing it can do. It is not a bug we can fix in the async API — but the capability you need already exists in this library's **reactive (RxJava) API**, and wiring it up is only a few lines.

**Why "just return a future" cannot be the fix**

Picture the client disconnected and reconnecting. Your app keeps calling `send()`, and each call hands a message to the library and moves on. There is no connection to drain them, so the library would have to hold every message (and its future) in memory. They accumulate until the process runs out of memory. The behavior you asked for — fire-and-forget while offline — is exactly what would kill the process.

During a long disconnect the messages must accumulate *somewhere*, and eventually something must **discard** some of them. The key point: **the client library cannot be the thing that decides what to discard.** It does not know which messages matter or what "too many" means for your application. Only your application has that authority — so your application must own the buffer and the drop policy.

The async `send(message) → CompletableFuture` shape gives it nowhere to do that: one message in, one future out, with no channel to say "slow down" and no way to hand you the drop decision. So its only options are block (today), accept-and-eventually-OOM, or silently drop. This is a limit of the API *shape*, not a defect — there is no change to `send()` that removes it.

**What to use instead: the reactive (RxJava) API**

The client library offers a second API — the reactive (RxJava) API — built for exactly this. It allows richer patterns of interaction between your application and the client than the async API can express. Instead of one-message-in / one-future-out, the client consumes a *source* of messages and pulls from it **only as fast as it can actually send** (Reactive Streams demand). When the client is offline it simply stops pulling — so nothing accumulates inside the library.

The important part for your case: you place a **bounded buffer with an overflow policy** in front of the publish, and *that* is where you control what happens when messages arrive faster than they can be sent — including during a long disconnect. You choose the bound and the policy (`DROP_OLDEST`, `DROP_LATEST`, or error-on-overflow); the library never has to guess which messages to drop. Sketch:

```java
// RxJava (already a dependency of this library — no extra module needed).
source.onBackpressureBuffer(
                10_000,                                          // bounded — never unbounded
                () -> LOG.warn("publish buffer full — dropping"),
                BackpressureOverflowStrategy.DROP_OLDEST)        // <-- your policy
        .compose(client::publish)                                // drains only as fast as it can send
        .subscribe(
                result -> { /* optional: per-message result */ },
                error  -> LOG.error("publish stream terminated", error));
```

That is the shape. It also supports much richer interaction when you want it: per-message delivery results, retry/resubscribe on errors, routing different topics through different policies, or combining with other reactive sources.

**And you can use this without changing your call sites**

If your code today just calls `publish(message)` and gets a `CompletableFuture` back, you can wrap the reactive setup behind the exact same signature. Feed the buffer from a *sink* — a push-in adapter — and hand back an already-completed future so your existing call sites do not change:

```java
final class BackpressuredPublisher {

    private final FlowableProcessor<Mqtt5Publish> sink =
            PublishProcessor.<Mqtt5Publish>create().toSerialized();  // thread-safe push-in point

    BackpressuredPublisher(Mqtt5RxClient client) {
        sink.onBackpressureBuffer(
                        10_000,                                          // bounded — never unbounded
                        () -> LOG.warn("publish buffer full — dropping"),
                        BackpressureOverflowStrategy.DROP_OLDEST)        // <-- your policy
                .compose(client::publish)                                // drains only as fast as it can send
                .subscribe(
                        result -> { /* optional: per-message result */ },
                        error  -> LOG.error("publish stream terminated", error));
    }

    // Same shape as async publish(): returns immediately, never blocks.
    CompletableFuture<Void> publish(Mqtt5Publish message) {
        sink.onNext(message);                 // handed to your buffer; never blocks
        return CompletableFuture.completedFuture(null);
    }
}
```

Wherever you call the async `publish(message)` today, you now call this one instead — same `CompletableFuture` return, but it never blocks. The buffer always accepts the message; when it is full, your overflow policy decides what leaves (with `DROP_OLDEST`, a completed future does **not** mean this message survived — an older one may have been dropped to make room). While the client is offline, the excess sits in *your* bounded buffer and your policy decides what to drop — instead of the async `send()` blocking the caller.

**This is just the starting point**

The example above is the minimal shape. Because the reactive API hands control to your application, you are not limited to it:

- The future here tells you only that the message reached your buffer, not that it reached the broker. If you want end-to-end delivery confirmation, complete each future from the publish *result* instead of immediately — subscribe to the result stream and resolve the matching future when the acknowledgement arrives.
- You can apply more elaborate overflow policies than a single `DROP_OLDEST` — for example, prioritising some topics over others, coalescing, or rate-limiting.
- You can replace the in-memory buffer with your own source entirely. The RxJava buffer operators are all **in-memory**; if you need to survive process restarts or buffer beyond available memory, back the source with a persistent store (a file, an embedded queue such as RocksDB or Chronicle Queue) and expose it as the reactive `source`. The publish side does not change — it just pulls from wherever you put the messages.

The point is that the reactive API gives your application the handle on the messages, so any policy your business semantics need is expressible — the async `send()` gives you none of these choices.

**Where this leaves us**

We are not going to treat this as a core bug in the async API, because it is not fixable there — this is not a matter of priority. For publishing that must tolerate disconnects, use the reactive API as above. We also see a genuine gap on our side: clearer documentation and examples on async-vs-reactive and offline/backpressure-sensitive publishing, which we intend to close.

**Related:** #620 is the same underlying behavior seen while *connected* (publishing faster than the broker acknowledges), plus an event-loop-thread deadlock. The same reactive setup is the answer there too.

Thanks again for reporting and documenting this so clearly.
