### ISSUE TITLE
AGP 8.0 java.lang.NoClassDefFoundError: ExternalSyntheticLambda2

### ISSUE THREAD

**Issue by rohit5ram** [hivemq/hivemq-mqtt-client#571]
Platform: Android 19
Application is crashing after upgrading to AGP 8.0

`Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttClientTransportConfigImplBuilder$$ExternalSyntheticLambda1>
18:12:54.480  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttClientTransportConfigImplBuilder$$ExternalSyntheticLambda1>
18:12:54.484  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttClientTransportConfigImplBuilder$$ExternalSyntheticLambda2>
18:12:54.484  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttClientTransportConfigImplBuilder$$ExternalSyntheticLambda2>
18:12:54.485  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttClientTransportConfigImplBuilder$$ExternalSyntheticLambda0>
18:12:54.486  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttClientTransportConfigImplBuilder$$ExternalSyntheticLambda0>
18:12:54.498  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda2>
18:12:54.498  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda2>
18:12:54.501  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda0>
18:12:54.501  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda0>
18:12:54.502  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda1>
18:12:54.504  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda1>
18:12:54.530  I  Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.LongAdderCounter>
18:12:54.530  I  Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.LongAdderCounter>
18:12:54.579  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilder$$ExternalSyntheticLambda0>
18:12:54.579  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilder$$ExternalSyntheticLambda0>
18:12:54.581  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilder$$ExternalSyntheticLambda1>
18:12:54.581  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilder$$ExternalSyntheticLambda1>
18:12:54.583  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilder$$ExternalSyntheticLambda2>
18:12:54.583  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilder$$ExternalSyntheticLambda2>
18:12:54.592  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClient$$ExternalSyntheticLambda3>
18:12:54.592  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClient$$ExternalSyntheticLambda3>
18:12:54.594  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClient$$ExternalSyntheticLambda2>
18:12:54.595  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClient$$ExternalSyntheticLambda2>
18:12:54.606  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClient$$ExternalSyntheticLambda4>
18:12:54.606  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClient$$ExternalSyntheticLambda4>
18:12:54.607  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClient$$ExternalSyntheticLambda1>
18:12:54.607  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClient$$ExternalSyntheticLambda1>
18:12:54.608  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClient$$ExternalSyntheticLambda5>
18:12:54.608  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClient$$ExternalSyntheticLambda5>
18:12:54.614  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.util.collections.ImmutableElement$ElementSpliterator>
18:12:54.614  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.util.collections.ImmutableElement$ElementSpliterator>
18:12:54.627  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttAsyncClient$$ExternalSyntheticLambda5>
18:12:54.627  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttAsyncClient$$ExternalSyntheticLambda5>
18:12:54.629  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttAsyncClient$$ExternalSyntheticLambda3>
18:12:54.629  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttAsyncClient$$ExternalSyntheticLambda3>
18:12:54.630  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttAsyncClient$$ExternalSyntheticLambda1>
18:12:54.631  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttAsyncClient$$ExternalSyntheticLambda1>
18:12:54.636  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttAsyncClient$$ExternalSyntheticLambda0>
18:12:54.637  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttAsyncClient$$ExternalSyntheticLambda0>
18:12:54.639  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.subscribe.MqttSubscriptionBuilder$$ExternalSyntheticLambda0>
18:12:54.639  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.subscribe.MqttSubscriptionBuilder$$ExternalSyntheticLambda0>
18:12:54.641  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.subscribe.MqttSubscribeBuilder$$ExternalSyntheticLambda2>
18:12:54.641  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.subscribe.MqttSubscribeBuilder$$ExternalSyntheticLambda2>
18:12:54.642  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.subscribe.MqttSubscribeBuilder$$ExternalSyntheticLambda3>
18:12:54.642  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.subscribe.MqttSubscribeBuilder$$ExternalSyntheticLambda3>
18:12:54.643  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.subscribe.MqttSubscribeBuilder$$ExternalSyntheticLambda3>
18:12:54.643  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.subscribe.MqttSubscribeBuilder$$ExternalSyntheticLambda1>
18:12:54.644  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.subscribe.MqttSubscribeBuilder$$ExternalSyntheticLambda1>
18:12:54.645  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.subscribe.MqttSubscribeBuilder$$ExternalSyntheticLambda0>
18:12:54.645  I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.message.subscribe.MqttSubscribeBuilder$$ExternalSyntheticLambda0>
18:12:54.648  I  Rejecting re-init on previously-failed class java.lang.Class<com.yantranet.signware.agent.mqtt.MqttUtils$$ExternalSyntheticLambda2>`

**Comment by rohit5ram** [comment]
@SgtSilvio Can you please help me? Its blocking!

**Comment by SgtSilvio** [comment]
Please share more information like minSdkVersion and Android version of your test device.
Also, do you use the android-retrofix plugin? If so, which version? Did you update to the latest version (0.5.0)?

**Comment by rohit5ram** [comment]
@SgtSilvio Updated the comment
`build.gradle:
minSdkVersion : 19
compileSdkVersion = 33
targetSdkVersion = 33
buildToolsVersion = '33.0.1'

Retrofix : 
classpath 'com.github.sgtsilvio.gradle:android-retrofix:0.5.0'
implementation "net.sourceforge.streamsupport:android-retrostreams:1.7.4"
implementation "net.sourceforge.streamsupport:android-retrofuture:1.7.4"

hivemq : implementation "com.hivemq:hivemq-mqtt-client-websocket:1.3.1"`

**Comment by SgtSilvio** [comment]
Can you share your build file.
Do you have everthikg configured as documented here: https://hivemq.github.io/hivemq-mqtt-client/docs/installation/android/

**Comment by rohit5ram** [comment]
@SgtSilvio I have configured everything as in https://hivemq.github.io/hivemq-mqtt-client/docs/installation/android/
Please find build.gradle files below

**project/library build.gradle**

```
apply plugin: 'com.android.library'
apply from: '../../constants.gradle'
android {
    compileSdkVersion project.ext.compileSdkVersion

    defaultConfig {
        minSdkVersion project.ext.minSdkVersion
        targetSdkVersion project.ext.targetSdkVersion
        consumerProguardFiles 'proguard-rules.pro'
        vectorDrawables.useSupportLibrary = true
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES.txt', 'META-INF/NOTICE.txt', 'META-INF/LICENSE.txt', 'META-INF/LICENSE']
        }
    }


    flavorDimensions "default"
    productFlavors {
        dev {
            setVersionName("DEV-" + rootProject.ext.releaseVersionName)
        }
        staging {
            setVersionName("STAGING-" + rootProject.ext.releaseVersionName)
        }
        production {}
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        dummy {
            initWith release
        }
    }


    configurations {
        all*.exclude group: 'com.google.android', module: 'android'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lint {
        abortOnError true
        checkReleaseBuilds true
    }
    namespace 'com.xxx.xxx.xxx'
//    testOptions.unitTests.includeAndroidResources true

    libraryVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "xxx-${variant.flavorName}-release.aar"
        }
        tasks.all { task ->
            if (task.name == "publish${variant.flavorName.capitalize()}PublicationToMavenLocal" ||
                    task.name == "publish${variant.flavorName.capitalize()}PublicationToXXXRepository") {
                task.dependsOn "assemble${variant.flavorName.capitalize()}Release"
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))
    implementation "com.squareup.okhttp3:okhttp:$project.ext.okHttpVersion"

    implementation "com.hivemq:hivemq-mqtt-client-websocket:$project.ext.hivemqLibVersion"
    implementation "androidx.localbroadcastmanager:localbroadcastmanager:$project.ext.supportXLibVersion"
   
    implementation "com.github.bumptech.glide:glide:$project.ext.glideVersion"
    implementation "com.github.kenglxn.QRGen:android:$project.ext.qRGenVersion"

    api "com.google.protobuf:protobuf-java:$project.ext.protobufJavaVersion"
    api "com.google.android.material:material:$project.ext.materialVersion"
    api "com.github.tony19:logback-android:$project.ext.tonyLogbackVersion"
    api("com.papertrailapp:logback-syslog4j:$project.ext.papertrailVersion") {
        exclude group: 'ch.qos.logback'
    }
    api "com.google.guava:guava:$project.ext.guavaVersion"
    implementation "com.google.android.gms:play-services-location:$project.ext.playServicesLocationVersion"

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.9'
    testImplementation 'org.mockito:mockito-core:4.5.1'
    testImplementation 'androidx.test:core:1.5.0'

    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test:rules:1.5.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
}
```

**project/app build.gradle**

```
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.github.sgtsilvio.gradle.android-retrofix'

apply from: '../constants.gradle'

def compileSdkVer = project.ext.compileSdkVersion
def buildToolsVer = project.ext.buildToolsVersion
android {
    compileSdkVersion compileSdkVer
    buildToolsVersion buildToolsVer

    defaultConfig {
        applicationId "xxx"
        minSdkVersion project.ext.minSdkVersion
        targetSdkVersion project.ext.targetSdkVersion
        versionName rootProject.ext.releaseVersionName
        versionCode rootProject.ext.releaseVersionCode
        multiDexEnabled true
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        vectorDrawables.useSupportLibrary = true
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES.txt', 'META-INF/NOTICE.txt', 'META-INF/LICENSE.txt', 'META-INF/LICENSE', 'META-INF/INDEX.LIST', 'META-INF/io.netty.versions.properties']
        }
    }


    signingConfigs {
        debug {
            storeFile file("debug.keystore")
        }
        release {
            storeFile file(System.getenv("xxx"))
            storePassword System.getenv("xxx")
            keyAlias System.getenv("xxx")
            keyPassword System.getenv("xxx")
        }
    }

    flavorDimensions "default"
    productFlavors {
        dev {
            setVersionName("DEV-" + rootProject.ext.releaseVersionName)
            applicationIdSuffix ".dev"
        }
        staging {
            setVersionName("STAGING-" + rootProject.ext.releaseVersionName)
            applicationIdSuffix ".staging"
        }
        production {}
    }
    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        dummy {
            initWith release
            versionNameSuffix "-DUMMY"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lint {
        abortOnError true
        checkReleaseBuilds true
    }
    namespace 'xxx'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':xxx')

    implementation "net.sourceforge.streamsupport:android-retrostreams:$project.ext.retrostreamsVersion"
    implementation "net.sourceforge.streamsupport:android-retrofuture:$project.ext.retrostreamsVersion"
    implementation "com.google.firebase:firebase-crashlytics:$project.ext.fbCrashlyticsVersion"
    implementation "com.google.firebase:firebase-analytics:$project.ext.fbAnalyticsVersion"
    implementation "androidx.lifecycle:lifecycle-process:$project.ext.lifecycleVersion"
    implementation "androidx.multidex:multidex:$project.ext.multidexVersion"
    implementation "com.google.android.gms:play-services-base:$project.ext.playServicesBaseVersion"

    // debugImplementation because LeakCanary should only run in debug builds.
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.10'
}

```
**project/build.gradle**

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.5'
        classpath 'gradle.plugin.com.github.sgtsilvio.gradle:android-retrofix:0.4.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://jitpack.io"
        }
//        mavenLocal()
    }
}

ext {
    releaseVersionName = version
    releaseVersionCode = project.buildVersionCode()
}
```

**Comment by SgtSilvio** [comment]
```

classpath 'gradle.plugin.com.github.sgtsilvio.gradle:android-retrofix:0.4.1'

```
This line in your project/build.gradle means that you are using 0.4.1 of android-retrofix, and not 0.5.0. Please try to update the version.

**Comment by rohit5ram** [comment]
@SgtSilvio I think the root cause is this error. Its not able to connect to the broker
`Could not find method javax.net.ssl.SSLParameters.setEndpointIdentificationAlgorithm, referenced from method com.hivemq.client.internal.mqtt.MqttClientSslConfigImpl$$ExternalSyntheticApiModelOutline0.m`

**Comment by Xcreen** [comment]
Get the same error as  [rohit5ram](https://github.com/rohit5ram).
I updated gradle from 7.4.2 to 8.0.2.
Using HiveMQ-Client 1.3.2 (also tested with 1.3.0 which worked under gradle 7.4.2) and android-retrofix 0.5.0.
Our minSDK is 23.  
Seems to work fine on android 9 but throw the error on android 6 devices.

Log:
```
2023-09-13 10:12:36.013 art                         I  Rejecting re-init on previously-failed class java.lang.Class<.service.MQTTBroadcastReceiverService$$ExternalSyntheticLambda2>
2023-09-13 10:12:36.013 art                         I  Rejecting re-init on previously-failed class java.lang.Class<.service.MQTTBroadcastReceiverService$$ExternalSyntheticLambda2>
2023-09-13 10:12:36.019 art                         I  Rejecting re-init on previously-failed class java.lang.Class<.service.MQTTBroadcastReceiverService$1>
2023-09-13 10:12:36.019 art                         I  Rejecting re-init on previously-failed class java.lang.Class<.service.MQTTBroadcastReceiverService$1>
2023-09-13 10:12:37.893 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttClientTransportConfigImplBuilder$$ExternalSyntheticLambda1>
2023-09-13 10:12:37.893 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttClientTransportConfigImplBuilder$$ExternalSyntheticLambda1>
2023-09-13 10:12:37.904 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttClientTransportConfigImplBuilder$$ExternalSyntheticLambda2>
2023-09-13 10:12:37.904 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttClientTransportConfigImplBuilder$$ExternalSyntheticLambda2>
2023-09-13 10:12:37.906 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttClientTransportConfigImplBuilder$$ExternalSyntheticLambda0>
2023-09-13 10:12:37.907 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttClientTransportConfigImplBuilder$$ExternalSyntheticLambda0>
2023-09-13 10:12:37.911 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda2>
2023-09-13 10:12:37.911 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda2>
2023-09-13 10:12:37.919 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda0>
2023-09-13 10:12:37.919 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda0>
2023-09-13 10:12:37.922 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda1>
2023-09-13 10:12:37.922 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda1>
2023-09-13 10:12:37.978 art                         I  Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.logging.Log4J2Logger>
2023-09-13 10:12:37.978 art                         I  Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.logging.Log4J2Logger>
2023-09-13 10:12:37.982 art                         I  Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.logging.Log4J2Logger>
2023-09-13 10:12:38.072 art                         I  Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.LongAdderCounter>
2023-09-13 10:12:38.072 art                         I  Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.LongAdderCounter>
2023-09-13 10:12:38.093 PlatformDependent           I  Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
2023-09-13 10:12:38.130 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilder$$ExternalSyntheticLambda0>
2023-09-13 10:12:38.131 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilder$$ExternalSyntheticLambda0>
2023-09-13 10:12:38.137 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilder$$ExternalSyntheticLambda1>
2023-09-13 10:12:38.137 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilder$$ExternalSyntheticLambda1>
2023-09-13 10:12:38.138 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilder$$ExternalSyntheticLambda2>
2023-09-13 10:12:38.139 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilder$$ExternalSyntheticLambda2>
2023-09-13 10:12:38.143 art                         I  Rejecting re-init on previously-failed class java.lang.Class<com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda1>
2023-09-13 10:12:38.144 System.err                  W  java.lang.NoClassDefFoundError: com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda1
2023-09-13 10:12:38.144 System.err                  W  	at com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase.transportConfig(MqttRxClientBuilderBase.java:131)
2023-09-13 10:12:38.144 System.err                  W  	at com.hivemq.client.internal.mqtt.MqttRxClientBuilder.transportConfig(MqttRxClientBuilder.java:39)
2023-09-13 10:12:38.144 System.err                  W  	at .service.MQTTBroadcastReceiverService.onHandleIntent(MQTTBroadcastReceiverService.java:122)
2023-09-13 10:12:38.144 System.err                  W  	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
2023-09-13 10:12:38.144 System.err                  W  	at android.os.Handler.dispatchMessage(Handler.java:102)
2023-09-13 10:12:38.144 System.err                  W  	at android.os.Looper.loop(Looper.java:148)
2023-09-13 10:12:38.144 System.err                  W  	at android.os.HandlerThread.run(HandlerThread.java:61)
2023-09-13 10:12:38.242 System.out                  I  ERROR:com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda1 | UncaughtException | java.lang.NoClassDefFoundError: com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase$$ExternalSyntheticLambda1
2023-09-13 10:12:38.242 System.out                  I  	at com.hivemq.client.internal.mqtt.MqttRxClientBuilderBase.transportConfig(MqttRxClientBuilderBase.java:131)
2023-09-13 10:12:38.242 System.out                  I  	at com.hivemq.client.internal.mqtt.MqttRxClientBuilder.transportConfig(MqttRxClientBuilder.java:39)
2023-09-13 10:12:38.242 System.out                  I  	at .service.MQTTBroadcastReceiverService.onHandleIntent(MQTTBroadcastReceiverService.java:122)
2023-09-13 10:12:38.242 System.out                  I  	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
2023-09-13 10:12:38.242 System.out                  I  	at android.os.Handler.dispatchMessage(Handler.java:102)
2023-09-13 10:12:38.242 System.out                  I  	at android.os.Looper.loop(Looper.java:148)
2023-09-13 10:12:38.242 System.out                  I  	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by rohit5ram** [comment]
@SgtSilvio I still face the issue. I cannot upgrade to AGP 8.0 anymore. Can you please help?
After following all suggestions mentioned above I am stuck with the below error,
```
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
                 java.lang.IllegalStateException: unknown type parameter 'I': class io.netty.handler.codec.MessageToMessageEncoder
```

**Comment by rohit5ram** [comment]
@SgtSilvio Finally it worked with below Proguard rules!
```
#HiveMQ
-keepclassmembernames class io.netty.** { *; }
-keepclassmembers class org.jctools.** { *; }
-keep class io.netty.handler.codec.** { *; }
```

**Comment by nktnet1** [comment]
@rohit5ram thanks for the rule:

```
-keep class io.netty.handler.codec.** { *; }
```

Without this, attempts to connect via WebSocket hangs indefinitely for me.
