### ISSUE TITLE
MqttAsyncClient sometimes blocking indefinitely on publish

### ISSUE THREAD

**Issue by tmbull** [hivemq/hivemq-mqtt-client#620]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/hivemq/hivemq-mqtt-client/issues?q=is%3Aissue).
- [ ] I've searched the project's [`discussions`](https://github.com/hivemq/hivemq-mqtt-client/discussions).

## ❓ Question

Hi all, I have a Vertx application that consumes messages from Kafka and publishes messages to MQTT. Frequently, I see threads get stuck in the "WAITING" state while publishing messages out. I looked through prior issues, and it seems that there are several cases where this can occur if the client is not connected before publishing, or the client gets disconnected before the publish is ack'ed. I do not believe that is the case here, as I do not see any messages indicating that the client has disconnected.

I do not believe this is a bug, as we have several other applications using the HiveMQ MqttClient to publish messages and we never encounter this issue. I have inspected the code, but to be honest, I am not very familiar with RxJava. I plan to dig into that next, but I was wondering if there are any other obvious cases or race conditions I look out for. Thank you for your time.

## 📎 Additional context

I would like to provide a sample project, but this is a proprietary code base and, as of yet, I have been unable to reproduce this code in a "toy" project.  However, here is a sample stack trace:

```
"vert.x-eventloop-thread-0" #21 prio=5 os_prio=0 cpu=84.25ms elapsed=135.84s tid=0x00007fdac4601000 nid=0x1b in Object.wait()  [0x00007fdaad038000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.16/Native Method)
	- waiting on <0x00000006951d1a00> (a com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables)
	at java.lang.Object.wait(java.base@11.0.16/Unknown Source)
	at com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables.add(MqttPublishFlowables.java:53)
	- waiting to re-lock in wait() <0x00000006951d1a00> (a com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables)
	at com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttAckSingle.subscribeActual(MqttAckSingle.java:56)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.hivemq.client.internal.rx.RxFutureConverter$RxSingleFuture.<init>(RxFutureConverter.java:113)
	at com.hivemq.client.internal.rx.RxFutureConverter.toFuture(RxFutureConverter.java:43)
	at com.hivemq.client.internal.mqtt.MqttAsyncClient.publish(MqttAsyncClient.java:243)
	at com.my.code.MqttClient.publishMessageWithRetryInternal(MqttClient.java:258)
	at com.avalara.edge.common.mqtt.MqttClient$$Lambda$1608/0x0000000840939440.handle(Unknown Source)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:948)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.ContextBase.emit(ContextBase.java:297)
	at io.vertx.core.impl.ContextInternal.emit(ContextInternal.java:207)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:937)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.16/Unknown Source)
```

**Comment by Mystery406** [comment]
Same as #554

**Comment by code2life-crypto** [comment]
@tmbull @Mystery406 Hi, We also encountered the same problem, do you have any solution? Thank you so much

Same as https://github.com/hivemq/hivemq-mqtt-client/issues/554, but we can not found any solution for this

**Comment by code2life-crypto** [comment]
@antpaw @Mystery406 @tmbull @grawinkel @dajudge Hi, we are facing the same issue, and we check the client state before each send. Here is the code for publish message:
<img width="1225" alt="ts20241012-1152-2" src="https://github.com/user-attachments/assets/d945aa77-eb32-4920-93fa-a3d1941e4789">

Under most circumstances, it runs fine in prod env. This is an intermittent issue that has occurred twice in the past six months, where the thread gets locked and cannot be awakened.

here is a sample stack trace:
`".client.pool-2-2" #157 [111] prio=5 os_prio=0 cpu=3198.07ms elapsed=100922.67s tid=0x00007fd7fbfac520 nid=111 in Object.wait()  [0x00007fd77e3f1000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait0(java.base@21.0.2/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@21.0.2/Object.java:366)
	at java.lang.Object.wait(java.base@21.0.2/Object.java:339)
	at com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables.add(MqttPublishFlowables.java:53)
	- locked <0x00000007220c0a30> (a com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables)
	at com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttAckSingle.subscribeActual(MqttAckSingle.java:56)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.hivemq.client.internal.rx.RxFutureConverter$RxSingleFuture.<init>(RxFutureConverter.java:113)
	at com.hivemq.client.internal.rx.RxFutureConverter.toFuture(RxFutureConverter.java:43)
	at com.hivemq.client.internal.mqtt.MqttAsyncClient.publish(MqttAsyncClient.java:243)`
	
here is "com.hivemq.client.mqtt" stack trace:
`"com.hivemq.client.mqtt-7-1" #176 [121] prio=10 os_prio=0 cpu=998.73ms elapsed=100918.76s tid=0x00007fd65c2a5220 nid=121 runnable  [0x00007fd77dceb000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:193)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:304)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:368)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.runWith(java.base@21.0.2/Thread.java:1596)
	at java.lang.Thread.run(java.base@21.0.2/Thread.java:1583)

"com.hivemq.client.mqtt-7-2" #175 [122] prio=10 os_prio=0 cpu=1038.93ms elapsed=100918.76s tid=0x00007fd674412360 nid=122 runnable  [0x00007fd77dbea000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:193)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:304)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:368)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.runWith(java.base@21.0.2/Thread.java:1596)
	at java.lang.Thread.run(java.base@21.0.2/Thread.java:1583)`

 
      **### Details**
      Affected HiveMQ MQTT Client version(s): 1.3.0
      Used JVM version: Oracle JDK 21+
      Used OS (name and version): deploy on AWS cloud Linux Debian AArch64
      Used MQTT version: N/A
      Used MQTT broker (name and version): N/A

We can't reproduce the issue in our local env, even after trying with breakpoints. We suspect that HiveMQ's thread pool doesn't always call the notifyAll method in certain cases, but we're unsure of the cause.
<img width="1446" alt="ts20241012-1210-2" src="https://github.com/user-attachments/assets/5a64c61e-5434-454d-b85d-6a398d2ef573">


Could you please help investigate this issue?

**Comment by lazyBisa** [comment]
Hitting the same problem. To me, it seems it happens when publishing with QOS 1 and the publishing happens faster than the acknowledges arrive. Essentially, the networking thread seems to be waiting on being allowed to publish while it it would instead need to receive the pending PubAck.
There seems to be a hardcoded cap of 64 in-flight messages in the MqttOutgoingQosHandler.
```java
    private static final int MAX_CONCURRENT_PUBLISH_FLOWABLES = 64; // TODO configurable

    @Override
    public void onSessionStartOrResume(
            final @NotNull MqttClientConnectionConfig connectionConfig, final @NotNull EventLoop eventLoop) {

        ....
        if (oldSendMaximum == 0) {
            publishFlowables.flatMap(
                    f -> f, true, MAX_CONCURRENT_PUBLISH_FLOWABLES, Math.min(newSendMaximum, Flowable.bufferSize()))
                    .subscribe(this);
            assert subscription != null;
            subscription.request(newSendMaximum);
        } else {
       ....
```
Not sure what that is for and if there is an issue with the implementation.

**Comment by lazyBisa** [comment]
@SgtSilvio do you have any input. Imho, there must be no this.wait(..) in the [MqttPublishFlowable#L53](https://github.com/hivemq/hivemq-mqtt-client/blame/79fffdfe78252e66710c7726a0681e2ae4c2f55c/src/main/java/com/hivemq/client/internal/mqtt/handler/publish/outgoing/MqttPublishFlowables.java#L53)

**Comment by mschoenert-hivemq** [comment]
Thanks for the detailed report — the stack trace points straight at the mechanism. This is the same underlying behavior as #554, seen from the *connected* side, plus one detail specific to your setup. I'll keep the shared part short since #554 covers it in full.

**The shared cause**

The async `send()` applies backpressure by **blocking the calling thread** when the publish path cannot accept more work, because `CompletableFuture send(message)` has no other way to signal "slow down." In #554 that happens because the client is offline. In your case it happens while fully connected: you publish faster than the broker acknowledges, the in-flight window fills, demand drops to zero, and the next `send()` blocks at `MqttPublishFlowables.add()`.

This is a limit of the async API *shape*, not a bug — accepting messages unbounded would just move the pile-up into the library until it OOMs, and the library is not the right place to decide which messages to drop. The full reasoning is in #554.

**The part specific to #620: the event-loop thread**

Your trace shows `send()` running on a **Vert.x event-loop thread**. That turns the block into a deadlock: the event loop is the very thread that would process the inbound PUBACKs that free the in-flight window and release the block — but it is stuck inside `send()`, so nothing wakes it. That is why it hangs indefinitely rather than briefly.

The first thing that follows: **never call the blocking async `send()` from an event-loop (or any single-threaded reactive) thread.** Blocking it can deadlock the machinery that would unblock it. But the robust fix is the same as for #554 — move to the reactive API, where a fast producer is throttled by real demand instead of a blocked thread.

**What to use instead: the reactive (RxJava) API**

The client library offers a second API — the reactive (RxJava) API — built for exactly this. It allows richer patterns of interaction between your application and the client than the async API can express. Instead of one-message-in / one-future-out, the client consumes a *source* of messages and pulls from it **only as fast as it can actually send** (Reactive Streams demand). When acknowledgements lag behind your publish rate, the client simply pulls more slowly — nothing blocks and nothing accumulates inside the library.

The important part for your case: you place a **bounded buffer with an overflow policy** in front of the publish, and *that* is where you control what happens when messages arrive faster than they can be sent. You choose the bound and the policy (`DROP_OLDEST`, `DROP_LATEST`, or error-on-overflow); the library never has to guess which messages to drop. Sketch:

```java
// RxJava (already a dependency of this library — no extra module needed).
source.onBackpressureBuffer(
                10_000,                                          // bounded — never unbounded
                () -> LOG.warn("publish buffer full — dropping"),
                BackpressureOverflowStrategy.DROP_OLDEST)        // <-- your policy
        .compose(client::publish)                                // drains only as fast as it can send
        .subscribe(
                result -> { /* optional: per-message result */ },
                error  -> LOG.error("publish stream terminated", error));
```

That is the shape. It also supports much richer interaction when you want it: per-message delivery results, retry/resubscribe on errors, routing different topics through different policies, or combining with other reactive sources.

**And you can use this without changing your call sites**

For a Kafka-to-MQTT bridge like yours, you do not have to restructure anything. If your code today just calls `publish(message)` and gets a `CompletableFuture` back, you can wrap the reactive setup behind the exact same signature. Feed the buffer from a *sink* — a push-in adapter — and hand back an already-completed future so your existing call sites do not change:

```java
final class BackpressuredPublisher {

    private final FlowableProcessor<Mqtt5Publish> sink =
            PublishProcessor.<Mqtt5Publish>create().toSerialized();  // thread-safe push-in point

    BackpressuredPublisher(Mqtt5RxClient client) {
        sink.onBackpressureBuffer(
                        10_000,                                          // bounded — never unbounded
                        () -> LOG.warn("publish buffer full — dropping"),
                        BackpressureOverflowStrategy.DROP_OLDEST)        // <-- your policy
                .compose(client::publish)                                // drains only as fast as it can send
                .subscribe(
                        result -> { /* optional: per-message result */ },
                        error  -> LOG.error("publish stream terminated", error));
    }

    // Same shape as async publish(): returns immediately, never blocks.
    CompletableFuture<Void> publish(Mqtt5Publish message) {
        sink.onNext(message);                 // handed to your buffer; never blocks
        return CompletableFuture.completedFuture(null);
    }
}
```

Wherever you call the async `publish(message)` today, you now call this one instead — same `CompletableFuture` return, but it never blocks. Because it never blocks, it is safe to call from your Vert.x event-loop thread — there is no wait for anything to unblock. The buffer always accepts the message; when it is full, your overflow policy decides what leaves (with `DROP_OLDEST`, a completed future does **not** mean this message survived — an older one may have been dropped to make room). When throughput outruns acknowledgements, the excess sits in *your* bounded buffer and your policy decides what to drop — instead of a blocked event loop.

**This is just the starting point**

The example above is the minimal shape. Because the reactive API hands control to your application, you are not limited to it:

- The future here tells you only that the message reached your buffer, not that it reached the broker. If you want end-to-end delivery confirmation, complete each future from the publish *result* instead of immediately — subscribe to the result stream and resolve the matching future when the acknowledgement arrives.
- You can apply more elaborate overflow policies than a single `DROP_OLDEST` — for example, prioritising some topics over others, coalescing, or rate-limiting.
- You can replace the in-memory buffer with your own source entirely. The RxJava buffer operators are all **in-memory**; if you need to survive process restarts or buffer beyond available memory, back the source with a persistent store (a file, an embedded queue such as RocksDB or Chronicle Queue) and expose it as the reactive `source`. The publish side does not change — it just pulls from wherever you put the messages.

The point is that the reactive API gives your application the handle on the messages, so any policy your business semantics need is expressible — the async `send()` gives you none of these choices.

**Where this leaves us**

As with #554, we are not going to fix this in the async API, because it cannot be fixed there — the blocking is the only safe behavior that signature allows. The path forward is the reactive API for backpressure-sensitive publishing, plus better documentation on our side (async-vs-reactive, and not blocking event-loop threads).

Thanks again — the event-loop detail in your trace made the diagnosis straightforward.
